### ISSUE TITLE
Undefined  extension point dita.conductor.pdf2flagging-preprocess.param

### ISSUE THREAD

**Issue by mohit162009** [dita-community/org.dita-community.pdf.flagging#1]
Hi, Greetings !
I am trying to install this plugin in my DITA-OT 2.5.1, But I'm getting an error:

![image](https://user-images.githubusercontent.com/30684610/28917382-1e574c6a-7863-11e7-852b-191d02285dbd.png)

I am a beginner, please pardon me if I am missing out something very basic. Thanks in advance.

Thanks and Best Regards,
Mohit

**Comment by drmacro** [comment]
This plugin only works with OT versions 1.7 and 1.8.5. OT 2.x has a completely different preprocessing framework and the flagging and filtering code has been completely rewritten.

**Comment by mohit162009** [comment]
Hello, Thanks a lot for the quick response. So how can I make it work with OT 2.x, Do you know any other plugin or can some modification be done to make it work with 2.x?

**Comment by mohit162009** [comment]
Hello, I am getting the same error in DITA OT 1.8.5 also.

![image](https://user-images.githubusercontent.com/30684610/28954862-ac877c02-78ff-11e7-9803-30642591dd7e.png)

Is there something else to take care of?

**Comment by mohit162009** [comment]
Okay, I added the patch and error are gone. But there is no bar in the output.
This is my ditamap file content:

`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map><title>Simple DITA Map Sample</title>
    <topicref href="topics/dita-map.dita" status="unchanged">
        <topicref href="topics/aligning-topics.dita"/>
    </topicref>
    <topicref href="topics/old-reference.dita" rev="deltaxml-delete" status="deleted"/>
    <topicref href="topics/topic-1page-demo.xml" status="unchanged"/>
    <topicref href="topics/new-reference.dita" rev="deltaxml-add" status="new"/>
</map>  `

**Comment by drmacro** [comment]
What FO engine are you using? FOP does not implement revision bars as far as I know--you need to use Antenna House or XEP.

You can check the generated FO to verify that the actual change bar markup is or is not there.
